
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dailyEasyRecipes_development
  username: postgres
  password: 
  port:
  host: 

test:
  <<: *default
  database: dailyEasyRecipes_test

production:
  <<: *default
  database: dailyEasyRecipes_production
  username: dailyEasyRecipes
  password: <%= ENV["DAILYEASYRECIPES_DATABASE_PASSWORD"] %>
