
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dailyEasyRecipes_development
  username: postgres
  password: 442002lol
  port: 5432
  host: localhost

test:
  <<: *default
  database: dailyEasyRecipes_test
  username: postgres
  password: 442002lol
  port: 5432
  host: localhost


production:
  <<: *default
  database: dailyEasyRecipes_production
  username: dailyEasyRecipes
  password: <%= ENV["DAILYEASYRECIPES_DATABASE_PASSWORD"] %>
